profile: dev-1.0
config:
  info: org.xs.assistant
  version: 2.0
datasource:
  url: jdbc:mysql://localhost:3306/xs?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
  username: root
  password: 123456
